import { ToolItem, AgentPreset, FeaturePillar, ExecutionLog } from '../types';

export const TOOLS_DATA: ToolItem[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'Developers',
    description: 'Create pull requests, manage issues, trigger actions, commit diffs, and inspect repository trees.',
    actionName: 'GITHUB_CREATE_PULL_REQUEST',
    iconName: 'GitPullRequest',
    badge: 'Popular',
    popularity: 99,
    sampleInput: {
      repo: 'org/production-app',
      title: 'feat: add streaming agent responses',
      head: 'agent/feature-stream',
      base: 'main',
      body: 'Automated PR generated by Claude Code via Composio tool execution.'
    },
    sampleOutput: {
      status: 201,
      pr_number: 842,
      url: 'https://github.com/org/production-app/pull/842',
      checks_passed: true
    }
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    description: 'Post messages, triage channels, listen to bot mentions, format blocks, and send alerts.',
    actionName: 'SLACK_POST_MESSAGE',
    iconName: 'MessageSquare',
    badge: 'Enterprise',
    popularity: 98,
    sampleInput: {
      channel: '#engineering-alerts',
      text: '🚨 P0 Sentry alert resolved and deployed to staging. PR #842 merged.',
      blocks: [{ type: 'section', text: 'Deployment verified in EU-Central.' }]
    },
    sampleOutput: {
      ok: true,
      channel: 'C04928130',
      ts: '1724921002.391200'
    }
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'Productivity',
    description: 'Query databases, generate formatted docs, append tasks, manage sprint roadmaps, and sync knowledge.',
    actionName: 'NOTION_CREATE_PAGE',
    iconName: 'FileText',
    badge: 'Popular',
    popularity: 96,
    sampleInput: {
      database_id: 'db_tasks_roadmap_2026',
      title: 'Q3 Agent Tooling Architecture Spec',
      properties: {
        Status: 'In Review',
        Priority: 'High',
        Assignee: 'Agent_Ops'
      }
    },
    sampleOutput: {
      id: 'page_9b2e8a1f',
      url: 'https://notion.so/composio/Q3-Agent-Tooling-Spec',
      created_time: '2026-08-29T08:14:00Z'
    }
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'Developers',
    description: 'File bug reports, triage issue cycles, transition project states, and assign engineering tickets.',
    actionName: 'LINEAR_CREATE_ISSUE',
    iconName: 'CheckSquare',
    badge: 'Dev Favorite',
    popularity: 97,
    sampleInput: {
      team_id: 'ENG',
      title: 'Fix unhandled token refresh in long-lived agent sandbox',
      priority: 1,
      labels: ['bug', 'agent-runtime', 'p0']
    },
    sampleOutput: {
      success: true,
      issue_id: 'ENG-4912',
      url: 'https://linear.app/team/issue/ENG-4912'
    }
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'DevOps',
    description: 'List unresolved runtime errors, fetch full stacktraces, inspect breadcrumbs, and resolve issues.',
    actionName: 'SENTRY_GET_LATEST_ISSUES',
    iconName: 'AlertTriangle',
    badge: 'DevOps',
    popularity: 94,
    sampleInput: {
      project: 'api-prod-cluster',
      query: 'is:unresolved level:error',
      limit: 10
    },
    sampleOutput: {
      count: 3,
      issues: [
        { id: 'SEN-9021', title: 'ConnectionResetError in RedisPool', events: 142 },
        { id: 'SEN-9022', title: 'RateLimitExceeded on Stripe webhook', events: 18 }
      ]
    }
  },
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Finance',
    description: 'Fetch subscription metrics, query customer MRR, handle refunds, and inspect invoice webhook states.',
    actionName: 'STRIPE_GET_CUSTOMER_BALANCE',
    iconName: 'CreditCard',
    badge: 'Finance',
    popularity: 95,
    sampleInput: {
      customer_id: 'cus_N8xL9p2Qv',
      expand: ['subscriptions', 'invoices']
    },
    sampleOutput: {
      mrr: '$4,800.00',
      status: 'active',
      plan: 'Scale Tier (1M tool calls/mo)'
    }
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'Communication',
    description: 'Search threads, compose context-aware drafts, apply smart labels, and extract attachment summaries.',
    actionName: 'GMAIL_SEND_EMAIL',
    iconName: 'Mail',
    badge: 'Core',
    popularity: 98,
    sampleInput: {
      to: 'client@enterprise.com',
      subject: 'Weekly Agent Workflow & ROI Summary',
      body: 'Hi Sarah, here is the automated report on 24,190 tasks executed this week.'
    },
    sampleOutput: {
      id: 'msg_18e9a2f7c',
      threadId: 'th_08912ba',
      sent: true
    }
  },
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Developers',
    description: 'Execute SQL queries, manage database rows, monitor vector embeddings, and invoke Edge functions.',
    actionName: 'SUPABASE_EXECUTE_SQL',
    iconName: 'Database',
    badge: 'Dev Favorite',
    popularity: 93,
    sampleInput: {
      query: 'SELECT user_id, count(*) as runs FROM agent_sessions GROUP BY 1 ORDER BY 2 DESC LIMIT 5;'
    },
    sampleOutput: {
      rowCount: 5,
      durationMs: 14,
      data: [{ user_id: 'usr_8172', runs: 1420 }, { user_id: 'usr_9910', runs: 890 }]
    }
  },
  {
    id: 'googlecalendar',
    name: 'Google Calendar',
    category: 'Productivity',
    description: 'Schedule team syncs, find free/busy times, reschedule conflicts, and generate Meet links.',
    actionName: 'CALENDAR_CREATE_EVENT',
    iconName: 'Calendar',
    badge: 'Productivity',
    popularity: 92,
    sampleInput: {
      summary: 'Product Architecture Review with Agents',
      start: '2026-08-30T15:00:00Z',
      durationMinutes: 45,
      attendees: ['lead@company.com', 'cto@company.com']
    },
    sampleOutput: {
      eventId: 'evt_998124',
      status: 'confirmed',
      meetUrl: 'https://meet.google.com/xyz-demo-app'
    }
  },
  {
    id: 'firecrawl',
    name: 'Firecrawl',
    category: 'AI & Search',
    description: 'Crawl entire websites, convert web pages into clean LLM-ready markdown, and scrape dynamic apps.',
    actionName: 'FIRECRAWL_SCRAPE_URL',
    iconName: 'Compass',
    badge: 'AI Search',
    popularity: 91,
    sampleInput: {
      url: 'https://news.ycombinator.com',
      formats: ['markdown', 'links']
    },
    sampleOutput: {
      markdown: '# Hacker News Top Stories\n1. AI Tool Execution Platform launches v3.0...',
      extractedLinksCount: 30
    }
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'DevOps',
    description: 'Trigger preview deployments, promote to production, inspect build logs, and manage domain DNS.',
    actionName: 'VERCEL_DEPLOY_PROJECT',
    iconName: 'Zap',
    badge: 'DevOps',
    popularity: 95,
    sampleInput: {
      projectId: 'prj_composio_agent_hub',
      target: 'production'
    },
    sampleOutput: {
      deploymentId: 'dpl_987x2la',
      url: 'https://agent-hub.vercel.app',
      readyState: 'READY'
    }
  },
  {
    id: 'datadog',
    name: 'Datadog',
    category: 'DevOps',
    description: 'Query telemetry, inspect APM traces, monitor container CPU/memory usage, and trigger monitors.',
    actionName: 'DATADOG_QUERY_METRICS',
    iconName: 'Activity',
    badge: 'Enterprise',
    popularity: 89,
    sampleInput: {
      query: 'avg:agent.execution.latency{env:production}',
      from: 'now-1h'
    },
    sampleOutput: {
      avgLatencyMs: 142.6,
      p99LatencyMs: 290.1,
      status: 'HEALTHY'
    }
  }
];

export const AGENT_PRESETS: AgentPreset[] = [
  {
    id: 'support-agent',
    name: 'Support & Triage Agent',
    role: 'Customer Operations',
    description: 'Monitors incoming Zendesk and Intercom tickets, queries GitHub issue trackers, and drafts verified technical solutions.',
    tools: ['Zendesk', 'GitHub', 'Slack', 'Notion'],
    activeTask: 'Resolved GH-482 bug & synced customer thread',
    status: 'active',
    recentEvent: 'Auto-closed 14 tickets with 98.4% satisfaction score'
  },
  {
    id: 'email-calendar-agent',
    name: 'Executive Copilot',
    role: 'Daily Office Work',
    description: 'Drafts responses to VIP emails, detects scheduling intents, resolves calendar conflicts, and compiles morning briefing decks.',
    tools: ['Gmail', 'Google Calendar', 'Google Docs', 'Slack'],
    activeTask: 'Scheduled 4 client meetings across 3 timezones',
    status: 'executing',
    recentEvent: 'Triaged 48 inbox items & organized schedule'
  },
  {
    id: 'code-review-agent',
    name: 'Automated PR Reviewer',
    role: 'Engineering & DevOps',
    description: 'Performs AST code analysis, runs sandboxed test suites, files Linear bugs for edge cases, and approves GitHub pull requests.',
    tools: ['GitHub', 'Linear', 'Sentry', 'Dynamic Sandbox'],
    activeTask: 'Reviewed PR #127 (Found 1 concurrency issue)',
    status: 'active',
    recentEvent: 'Approved 18 PRs and ran 112 sandboxed unit tests'
  },
  {
    id: 'sql-analytics-agent',
    name: 'SQL & Business BI Agent',
    role: 'Finance & Ops',
    description: 'Translates natural language questions into safe PostgreSQL queries, joins Stripe payment cohorts, and updates Google Sheets.',
    tools: ['Supabase', 'Stripe', 'Google Sheets', 'PostgreSQL'],
    activeTask: 'Calculated August Net Dollar Retention: 134%',
    status: 'active',
    recentEvent: 'Generated 12 daily financial executive summaries'
  },
  {
    id: 'sentry-devops-agent',
    name: 'Incident Response Agent',
    role: 'SRE & Infrastructure',
    description: 'Listens for P0 Sentry alerts, matches stacktraces to git blame history, spins up fix branches, and pings on-call engineers in Slack.',
    tools: ['Sentry', 'Datadog', 'GitHub', 'Slack', 'PagerDuty'],
    activeTask: 'Patched Redis memory leak & initiated canary build',
    status: 'executing',
    recentEvent: 'MTTR reduced from 42 mins to 2.8 mins'
  },
  {
    id: 'deep-research-agent',
    name: 'Market & Web Research Agent',
    role: 'Strategy & Growth',
    description: 'Executes Firecrawl web scraping across competitor documentation, synthesizes structured datasets, and exports to Notion.',
    tools: ['Firecrawl', 'Notion', 'Google Docs', 'Perplexity'],
    activeTask: 'Synthesized 28 competitor pricing models into table',
    status: 'standby',
    recentEvent: 'Extracted 140 verified citations into Notion DB'
  }
];

export const FEATURE_PILLARS: FeaturePillar[] = [
  {
    id: 'smart-tools',
    num: '01',
    title: 'Search that thinks',
    subtitle: 'SMART TOOLS',
    description: 'Save your agent’s context window for reasoning. Only deliver the exact right tool schema at the exact millisecond needed.',
    badge: 'JIT Tool Discovery',
    points: [
      'Tools resolved dynamically by intent, not static prompt bloat',
      'Automatic parameter pruning reduces LLM token consumption by 84%',
      'Proposed execution plans with built-in guardrails for complex workflows',
      'Handles thousands of potential tools without degrading model reasoning'
    ],
    codeSample: `// Just-in-time tool resolution by natural language intent
const tools = await session.searchTools({
  query: "triage sentry error and file linear ticket",
  limit: 2
});

// Returns ONLY: SENTRY_GET_ISSUE + LINEAR_CREATE_ISSUE schemas`
  },
  {
    id: 'constant-evolution',
    num: '02',
    title: 'Tools that learn & auto-heal',
    subtitle: 'CONSTANT EVOLUTION',
    description: 'Your tools get sharper every single day. Real agent behavior at massive scale makes Composio tools the most accurate available.',
    badge: 'Self-Healing Schemas',
    points: [
      'Accuracy driven by over 50,000,000 real-world tool executions',
      'Automatic fallback handling when third-party upstream APIs update',
      'Account-level parameter memory for your organizational conventions',
      'API-stable, agent-optimized responses formatted for LLM comprehension'
    ],
    codeSample: `// Auto-healing parameter normalization
const result = await session.execute("SLACK_SEND_MESSAGE", {
  channel: "general", // Auto-resolves channel name to C0184920
  text: "Morning briefing ready!"
});`
  },
  {
    id: 'end-user-auth',
    num: '03',
    title: 'Auth that simply works',
    subtitle: 'END USER AUTH',
    description: 'Stop debugging broken OAuth flows and revoked tokens. Composio handles the entire authentication lifecycle on the fly.',
    badge: 'Delegated Managed Auth',
    points: [
      'Fully managed OAuth 2.0, API keys, and service tokens out of the box',
      'Inline instant auth popups triggered by user intent inside agent chats',
      'Granular scope minimization that tightens permissions per action',
      'SOC-2 Type II compliant token encryption with KMS isolation'
    ],
    codeSample: `// Inline authorization check & instant auth URL generation
const auth = await session.authorize("github", {
  scopes: ["repo", "workflow"]
});

if (auth.status === "REQUIRED") {
  return "Please connect your GitHub: " + auth.connectUrl;
}`
  },
  {
    id: 'dynamic-sandbox',
    num: '04',
    title: 'Programmatic execution',
    subtitle: 'DYNAMIC SANDBOX',
    description: 'Remote, isolated microVM sandboxes where tools execute as fast Python / TS code and large results live in a navigable filesystem.',
    badge: 'Isolated MicroVMs',
    points: [
      'Compose tools as pure code — loops, batching, and sub-LLM calls',
      'Gigabyte responses stored in remote filesystem your agent browses lazily',
      'Ephemeral security isolation: zero data leaks between executions',
      'Sub-50ms warm cold-starts with Python 3.11 and Node.js preloaded'
    ],
    codeSample: `# Run in ephemeral Composio microVM sandbox
issues = run_composio_tool('SENTRY_LIST_ISSUES', project='api-prod')
for issue in issues[:5]:
    trace = run_composio_tool('SENTRY_GET_EVENT', issue_id=issue['id'])
    if 'P0' in issue['tags']:
        run_composio_tool('LINEAR_CREATE_ISSUE', title=issue['title'], priority=1)`
  }
];

export const CODE_SNIPPETS = {
  python: `from composio import Composio, Action
from openai import OpenAI

client = OpenAI()
composio = Composio(api_key="comp_live_98x...")

# 1. Initialize session with your user ID
session = composio.create_session(user_id="user_alex")

# 2. Get intelligent tool definitions for agent
tools = session.get_tools(actions=[
    Action.GITHUB_CREATE_PULL_REQUEST,
    Action.SLACK_POST_MESSAGE,
    Action.NOTION_CREATE_PAGE
])

# 3. Give directly to any LLM harness
response = client.chat.completions.create(
    model="gpt-4o",
    messages=[{"role": "user", "content": "Create PR for auth fix and notify team in Slack"}],
    tools=tools
)

# 4. Execute tool call with 1 line
result = session.handle_tool_call(response.choices[0].message.tool_calls[0])
print(f"Tool executed: {result.status_code} - {result.data}")`,

  typescript: `import { Composio } from "@composio/core";
import { Anthropic } from "@anthropic-ai/sdk";

const anthropic = new Anthropic();
const composio = new Composio({ apiKey: process.env.COMPOSIO_API_KEY });

// 1. Create a context-aware session
const session = await composio.createSession({ userId: "user_4912" });

// 2. Fetch scoped tools
const tools = await session.getTools({
  actions: ["GITHUB_CREATE_PULL_REQUEST", "LINEAR_CREATE_ISSUE"]
});

// 3. Execute with Claude 3.7 Sonnet
const message = await anthropic.messages.create({
  model: "claude-3-7-sonnet-20250219",
  max_tokens: 1024,
  messages: [{ role: "user", content: "File Linear issue for Sentry error #9021" }],
  tools: tools
});

// 4. Handle response seamlessly
const execution = await session.executeToolCall(message.content);
console.log("Execution Result:", execution.data);`,

  langchain: `from composio_langchain import ComposioToolSet, Action
from langchain_anthropic import ChatAnthropic

# Wrap Composio tools into standard LangChain BaseTool interface
toolset = ComposioToolSet(api_key="comp_live_...")
tools = toolset.get_tools(actions=[Action.GMAIL_SEND_EMAIL, Action.CALENDAR_CREATE_EVENT])

llm = ChatAnthropic(model="claude-3-7-sonnet-20250219")
llm_with_tools = llm.bind_tools(tools)

# Runs full multi-step LangChain agent with automatic auth handling
res = llm_with_tools.invoke("Check my afternoon calendar and draft replies to urgent emails")`,

  crewai: `from crewai import Agent, Task, Crew
from composio_crewai import ComposioToolSet, Action

composio_tools = ComposioToolSet()
tools = composio_tools.get_tools(actions=[
    Action.FIRECRAWL_SCRAPE_URL,
    Action.NOTION_CREATE_PAGE
])

researcher = Agent(
    role="Senior Market Analyst",
    goal="Investigate competitor agent frameworks and document to Notion",
    tools=tools,
    verbose=True
)

task = Task(
    description="Scrape target technical docs and create structured summary",
    agent=researcher
)

Crew(agents=[researcher], tasks=[task]).kickoff()`
};

export const MOCK_EXECUTION_STREAM: ExecutionLog[] = [
  {
    id: 'log-1',
    timestamp: 'Just now',
    agent: 'Claude 3.7 Sonnet',
    tool: 'SENTRY_GET_LATEST_ISSUES',
    status: '200 OK',
    durationMs: 38,
    payload: '{"project": "api-prod", "unresolved": 2}'
  },
  {
    id: 'log-2',
    timestamp: '1s ago',
    agent: 'Claude 3.7 Sonnet',
    tool: 'LINEAR_CREATE_ISSUE',
    status: '200 OK',
    durationMs: 64,
    payload: '{"team": "ENG", "key": "ENG-4912", "priority": 1}'
  },
  {
    id: 'log-3',
    timestamp: '3s ago',
    agent: 'Cursor Agent',
    tool: 'GITHUB_CREATE_PULL_REQUEST',
    status: '200 OK',
    durationMs: 112,
    payload: '{"pr": 842, "branch": "fix/auth-leak"}'
  },
  {
    id: 'log-4',
    timestamp: '5s ago',
    agent: 'OpenClaw Agent',
    tool: 'SLACK_POST_MESSAGE',
    status: '200 OK',
    durationMs: 44,
    payload: '{"channel": "#eng", "text": "PR #842 ready for review"}'
  },
  {
    id: 'log-5',
    timestamp: '8s ago',
    agent: 'Opus 4.6 Copilot',
    tool: 'STRIPE_GET_CUSTOMER_BALANCE',
    status: '200 OK',
    durationMs: 82,
    payload: '{"mrr": "$4,800.00", "plan": "Enterprise"}'
  }
];
